### ISSUE TITLE
Possibility to select the same references as in https://clades.nextstrain.org/ ?

### ISSUE THREAD

**Issue by jocketuffing** [nextstrain/seasonal-flu#208]
Thanks for a great nextstrain workflow.

I would like to ask for an update to have the possibility to select the reference sequences that are available at https://clades.nextstrain.org/ ?

Particularly I'm thinking about using A/Darwin/6/2021 instead of the default A/Wisconsin/67/2005 for H3N2.

Best
Olov

**Comment by huddlej** [comment]
Hi @jocketuffing! You can set the reference FASTA and gene map GFF for your builds to any path you like in your builds configuration file. The Nextclade references you see on clades.nextstrain.org live in this repository in the `nextclade/dataset_config/` directory, so you could point your build config at these files. Here is an example snippet of an updated version of [our simple config that runs in our GitHub CI action](https://github.com/nextstrain/seasonal-flu/blob/master/profiles/ci/builds.yaml):

```yaml
segments:
  - ha

builds:
    "ci_build":
      lineage: h3n2
      reference: "nextclade/dataset_config/h3n2/ha/EPI1857216/reference.fasta"
      annotation: "nextclade/dataset_config/h3n2/ha/EPI1857216/annotation.gff"
```

Notice that the Nextclade references are grouped by segment and accession, so there isn't an easy way to set your reference and annotation paths in the config to a generic path like `config/h3n2/{segment}/reference.fasta`. However, you could setup your local directory structure to mimic that same pattern of nesting files by segment only and then copy the Nextclade files you need into that structure.

**Comment by jocketuffing** [comment]
Dear @huddlej , 

Thank you so much for your reply. Unfortunately I am still having issues.
I have replicated the gisaid example from the [README](https://github.com/nextstrain/seasonal-flu/blob/master/README.md).
I also set the submission dates as the collection dates to reduce to ~1800 seqs.

It works fine using the build provided. 
`head -n 30 builds/h3n2/ha/clades.json`

`{
  "branches": {
    "NODE_0000005": {
      "labels": {
        "clade": "2"
      }
    },
    "NODE_0000006": {
      "labels": {
        "clade": "2b"
      }
    },
    "NODE_0000012": {
      "labels": {
        "clade": "2a"
      }
    },
    "NODE_0000013": {
      "labels": {
        "clade": "2a.1b"
      }
    },
    "NODE_0000017": {
      "labels": {
        "clade": "2a.3"
      }
    },
    "NODE_0000021": {
      "labels": {
        "clade": "2a.3a.1"`

But when I edit the build file as suggested, clade assignment is not working and branches appears empty:
`head -n 30 builds/h3n2_ref/ha/clades.json`

`{
  "branches": {},
  "generated_by": {
    "program": "augur",
    "version": "26.1.0"
  },
  "nodes": {
    "A/Beijing-Huairou/1626/2023": {
      "clade_membership": "unassigned"
    },
    "A/Bolivia/1548/2023": {
      "clade_membership": "unassigned"
    },
    "A/Canberra/206/2023": {
      "clade_membership": "unassigned"
    },
    "A/Catalonia/NSVH102169806/2023": {
      "clade_membership": "unassigned"
    },
    "A/Catalonia/NSVH102175022/2023": {
      "clade_membership": "unassigned"
    },
    "A/Catalonia/NSVH161516212/2023": {
      "clade_membership": "unassigned"
    },
    "A/Catalonia/NSVH171605044/2023": {
      "clade_membership": "unassigned"
    },
    "A/Chipata/14-NIC-008/2023": {
      "clade_membership": "unassigned"`

I can not see what I am doing wrong. Here is the build file I am using where build, reference and annotation has been edited:

```
custom_rules:
  - profiles/gisaid/prepare_data.smk

metadata_fields:
  - Isolate_Name
  - Isolate_Id
  - Passage_History
  - Location
  - Authors
  - Originating_Lab
  - Collection_Date
  - Submission_Date
renamed_metadata_fields:
  - strain
  - accession
  - passage
  - location
  - authors
  - originating_lab
  - date
  - date_submitted

lat-longs: "config/lat_longs.tsv"

segments:
  - ha

submission_date_field: date_submitted
recency:
  date_bins: [7, 30, 90]
  date_bin_labels: ["last week", "last month", "last quarter"]
  upper_bin_label: older

builds:
    "h3n2_ref":
      lineage: h3n2
      reference: "nextclade/dataset_config/h3n2/ha/EPI1857216/reference.fasta"
      annotation: "nextclade/dataset_config/h3n2/ha/EPI1857216/annotation.gff"
      tree_exclude_sites: "config/h3n2/{segment}/exclude-sites.txt"
      clades: "config/h3n2/ha/clades.tsv"
      subclades: "config/h3n2/ha/subclades.tsv"
      auspice_config: "config/h3n2/auspice_config.json"
      enable_lbi: true
      enable_glycosylation: true
      subsamples:
        global:
            filters: "--group-by region year month --subsample-max-sequences 100"
```

**Comment by huddlej** [comment]
@jocketuffing Sorry about that! It's not you, it's us. The Darwin/6 reference has different nucleotide coordinates than the Wisconsin reference, so the clade definitions that depend on nucleotide positions no longer match. Since the workflow downloads the clade and subclade definitions from GitHub, you don't want to modify those files locally. Instead, you could modify `profiles/gisaid/prepare_data.smk` to look like the following where I've added two new rules at the end (and `ruleorder` directives) that download clade definitions and update the nucleotide offsets by a value you provide in the build configuration.

```snakemake
ruleorder: prepare_sequences > parse
ruleorder: prepare_metadata > annotate_metadata_with_reference_strains
ruleorder: download_and_offset_clades > download_clades
ruleorder: download_and_offset_subclades > download_subclades

# Assumes that metadata XLS is the XLS metadata file downloaded from GISAID for
# the same samples that appear in the raw sequences FASTA below.
#
# 1. Convert metadata from XLS to CSV for better downstream parsing.
# 2. Select only the metadata fields that we need.
# 3. Rename GISAID fields to Nextstrain standard field names.
# 4. Split the "location" field into four separate geographic fields with standard Nextstrain field names.
# 5. Remove whitespace in strain names to make names consistent with the sequence records as processed below.
# 6. Sort records in descending order by strain name and accession such that the most recent accession for each strain appears first.
# 7. Select the first record for each unique strain name in the metadata, keeping the most recent accession.
rule prepare_metadata:
    input:
        metadata="data/{lineage}/metadata.xls",
    output:
        metadata="data/{lineage}/metadata.tsv",
    params:
        old_fields=",".join(config["metadata_fields"]),
        new_fields=",".join(config["renamed_metadata_fields"]),
    conda: "../../workflow/envs/nextstrain.yaml"
    shell:
        """
        python3 scripts/xls2csv.py --xls {input.metadata} --output /dev/stdout \
            | csvtk cut -f {params.old_fields} \
            | csvtk rename -f {params.old_fields} -n {params.new_fields} \
            | csvtk sep -f location --na "N/A" --names region,country,division,location --merge --num-cols 4 --sep " / " \
            | csvtk replace -f strain -p " " -r "" \
            | csvtk sort -k strain,accession:r \
            | csvtk uniq -T -f strain > {output.metadata}
        """

# Assumes that "raw sequences" FASTA is downloaded from GISAID with only the
# "Isolate_name" field selected such that each record looks like:
# ">strain name|accession".
#
# 1. Remove spaces from strain names.
# 2. Add unique id to duplicate strain name and accession pairs.
# 3. Sort sequences in descending order by strain and accession (latest accession comes first).
# 4. Replace "|" character with space, changing record name to strain name only.
# 5. Keep the first sequence for a given strain name, keeping the sequence for the most recent accession.
rule prepare_sequences:
    input:
        sequences="data/{lineage}/raw_sequences_{segment}.fasta",
    output:
        sequences="data/{lineage}/{segment}.fasta",
    conda: "../../workflow/envs/nextstrain.yaml"
    shell:
        """
        seqkit replace -p " " -r "" {input.sequences} \
            | seqkit rename \
            | seqkit sort -n -r \
            | seqkit replace -p "\|" -r " " \
            | seqkit rmdup > {output.sequences}
        """

rule download_and_offset_clades:
    output:
        clades="config/{lineage}/{segment}/clades.tsv",
    conda: "../../workflow/envs/nextstrain.yaml"
    params:
        url=lambda wildcards: clade_url_by_lineage_and_segment.get(wildcards.lineage, {}).get(wildcards.segment),
        offset=lambda wildcards: config.get("reference_offsets", {}).get(wildcards.lineage, {}).get(wildcards.segment, 0),
    shell:
        """
        curl "{params.url}" \
            | perl -F'\\t' -ne '$F[2]+={params.offset} if $F[1] =~ "nuc"; print join "\\t", @F' > {output.clades}
        """

rule download_and_offset_subclades:
    output:
        subclades="config/{lineage}/{segment}/subclades.tsv",
    conda: "../../workflow/envs/nextstrain.yaml"
    params:
        url=lambda wildcards: subclade_url_by_lineage_and_segment.get(wildcards.lineage, {}).get(wildcards.segment),
        offset=lambda wildcards: config.get("reference_offsets", {}).get(wildcards.lineage, {}).get(wildcards.segment, 0),
    shell:
        """
        curl "{params.url}" \
            | perl -F'\\t' -ne '$F[2]+={params.offset} if $F[1] =~ "nuc"; print join "\\t", @F' > {output.subclades}
        """
```

The rules above default to a nucleotide position offset of 0 when you haven't defined an offset in the build configuration. The following shows an alternate `profiles/gisaid/builds.yaml` that uses the Darwin/6 reference and also specifies the required lineage- and segment-specific offset for the nucleotide coordinates (-17).

```yaml
custom_rules:
  - profiles/gisaid/prepare_data.smk

metadata_fields:
  - Isolate_Name
  - Isolate_Id
  - Passage_History
  - Location
  - Authors
  - Originating_Lab
  - Collection_Date
  - Submission_Date
renamed_metadata_fields:
  - strain
  - accession
  - passage
  - location
  - authors
  - originating_lab
  - date
  - date_submitted

lat-longs: "config/lat_longs.tsv"

segments:
  - ha

submission_date_field: date_submitted
recency:
  date_bins: [7, 30, 90]
  date_bin_labels: ["last week", "last month", "last quarter"]
  upper_bin_label: older

reference_offsets:
  h3n2:
    ha: -17

builds:
    "h3n2":
      lineage: h3n2
      reference: "nextclade/dataset_config/h3n2/ha/EPI1857216/reference.fasta"
      annotation: "nextclade/dataset_config/h3n2/ha/EPI1857216/annotation.gff"
      tree_exclude_sites: "config/h3n2/{segment}/exclude-sites.txt"
      clades: "config/h3n2/ha/clades.tsv"
      subclades: "config/h3n2/ha/subclades.tsv"
      auspice_config: "config/h3n2/auspice_config.json"
      enable_lbi: true
      enable_glycosylation: true
      subsamples:
        global:
            filters: "--group-by region year month --subsample-max-sequences 100"
```

When you run the workflow with these modifications, you should see that the clades and subclades are assigned as expected. Does this work for you?

This simple use case that you're trying to achieve reveals a couple of sharp edges in the current workflow that we should address including 1) [allowing the reference/annotation configuration to vary by segment within a lineage](https://github.com/nextstrain/seasonal-flu/issues/209) and 2) [allowing users to define their own reference sequence offsets for clade definitions](https://github.com/nextstrain/seasonal-flu/issues/210).

**Comment by jocketuffing** [comment]
@huddlej thanks for excellent support. I can confirm that using the instructions above works for me.


Let me just try to run it using my own favourite reference, A/Cambodia/e0826360/2020, and then we can close this.

**Comment by jocketuffing** [comment]
@huddlej I would say that I have managed to set to an arbitrary reference to A/Cambodia/e0826360/2020. But, I include this sequence in the input fasta and I get mutations compared to the reference! These mutations are expected to appear when using A/Darwin/6/2021 btw. Please have a look at the output file muts.json where the 'sequence' of A/Cambodia/e0826360/2020 is identical to the 'nuc' in the 'reference'. You may also notice that, A/Darwin/6/2021, which I also include in the input fasta, has no mutations but it's sequence differs from the reference.

muts.json is attached.

[muts.json](https://github.com/user-attachments/files/18766829/muts.json)

**Comment by huddlej** [comment]
@jocketuffing I didn't have time to try this out today, but my first thought is that what you're seeing might reflect the fact that our workflow adds a parent node to the most recent common ancestor to track mutations between that ancestor and the reference. This approach could cause mutations to appear on the branch to the reference in the tree, even those those mutations aren't present in the "reference" sequence in the muts JSON. You can find [details about this in our docs](https://docs.nextstrain.org/en/latest/guides/bioinformatics/root-and-ref-seqs.html).

I will doublecheck tomorrow by trying out the same reference you mentioned above. Can you post the contents of your build configuration YAML file here, too, just so I can get as close as possible to the same environment you're running in?

**Comment by jocketuffing** [comment]
Thank you @huddlej.

I have read the suggested and tried all type of modifications of snakemake files to "enabling mutation-calling against the reference sequence", where reference is A/Cambodia/e0826360/2020, but without success.

One other issue I get is that A/Cambodia/e0826360/2020 gets the clade_membership assigned to 3C.2 and not to 1a as I do from the same sequence on https://clades.nextstrain.org/ using Reference: A/Darwin/6/2021 (EPI1857216).

When I revert back to the predefined reference A/Darwin/6/2021, the clade_membership for A/Cambodia/e0826360/2020 becomes 2a! A different strain, A/Cambodia/925256/2020 correctly gets 1a for all methods.

I understand it is time consuming but I am very grateful for your help.

Here comes the config content I have for running with reference A/Darwin/6/2021.

`cat profiles/gisaid/h3n2_2024.yaml`

```
builds:
  h3n2_2024_2025-02-13_1232:
    annotation: nextclade/dataset_config/h3n2/ha/EPI1857216/annotation.gff
    auspice_config: config/h3n2/auspice_config.json
    clades: config/h3n2/ha/clades.tsv
    enable_glycosylation: true
    enable_lbi: true
    lineage: h3n2
    reference: nextclade/dataset_config/h3n2/ha/EPI1857216/reference.fasta
    subclades: config/h3n2/ha/subclades.tsv
    subsamples:
      global:
        filters: ''
    tree_exclude_sites: config/h3n2/{segment}/exclude-sites.txt
custom_rules:
- profiles/gisaid/prepare_data_mod.smk
lat-longs: config/lat_longs.tsv
metadata_fields:
- Isolate_Name
- Isolate_Id
- Passage_History
- Location
- Authors
- Originating_Lab
- Collection_Date
- Submission_Date
recency:
  date_bin_labels:
  - last week
  - last month
  - last quarter
  date_bins:
  - 7
  - 30
  - 90
  upper_bin_label: older
reference_offsets:
  h3n2:
    ha: -17
renamed_metadata_fields:
- strain
- accession
- passage
- location
- authors
- originating_lab
- date
- date_submitted
segments:
- ha
submission_date_field: date_submitted
```

below as proposed...
```cat profiles/gisaid/prepare_data_mod.smk```

```
ruleorder: prepare_sequences > parse
ruleorder: prepare_metadata > annotate_metadata_with_reference_strains
ruleorder: download_and_offset_clades > download_clades
ruleorder: download_and_offset_subclades > download_subclades

# Assumes that metadata XLS is the XLS metadata file downloaded from GISAID for
# the same samples that appear in the raw sequences FASTA below.
#
# 1. Convert metadata from XLS to CSV for better downstream parsing.
# 2. Select only the metadata fields that we need.
# 3. Rename GISAID fields to Nextstrain standard field names.
# 4. Split the "location" field into four separate geographic fields with standard Nextstrain field names.
# 5. Remove whitespace in strain names to make names consistent with the sequence records as processed below.
# 6. Sort records in descending order by strain name and accession such that the most recent accession for each strain appears first.
# 7. Select the first record for each unique strain name in the metadata, keeping the most recent accession.
rule prepare_metadata:
    input:
        metadata="data/{lineage}/metadata.xls",
    output:
        metadata="data/{lineage}/metadata.tsv",
    params:
        old_fields=",".join(config["metadata_fields"]),
        new_fields=",".join(config["renamed_metadata_fields"]),
    conda: "../../workflow/envs/nextstrain.yaml"
    shell:
        """
        python3 scripts/xls2csv.py --xls {input.metadata} --output /dev/stdout \
            | csvtk cut -f {params.old_fields} \
            | csvtk rename -f {params.old_fields} -n {params.new_fields} \
            | csvtk sep -f location --na "N/A" --names region,country,division,location --merge --num-cols 4 --sep " / " \
            | csvtk replace -f strain -p " " -r "" \
            | csvtk sort -k strain,accession:r \
            | csvtk uniq -T -f strain > {output.metadata}
        """

# Assumes that "raw sequences" FASTA is downloaded from GISAID with only the
# "Isolate_name" field selected such that each record looks like:
# ">strain name|accession".
#
# 1. Remove spaces from strain names.
# 2. Add unique id to duplicate strain name and accession pairs.
# 3. Sort sequences in descending order by strain and accession (latest accession comes first).
# 4. Replace "|" character with space, changing record name to strain name only.
# 5. Keep the first sequence for a given strain name, keeping the sequence for the most recent accession.
rule prepare_sequences:
    input:
        sequences="data/{lineage}/raw_sequences_{segment}.fasta",
    output:
        sequences="data/{lineage}/{segment}.fasta",
    conda: "../../workflow/envs/nextstrain.yaml"
    shell:
        """
        seqkit replace -p " " -r "" {input.sequences} \
            | seqkit rename \
            | seqkit sort -n -r \
            | seqkit replace -p "\|" -r " " \
            | seqkit rmdup > {output.sequences}
        """

rule download_and_offset_clades:
    output:
        clades="config/{lineage}/{segment}/clades.tsv",
    conda: "../../workflow/envs/nextstrain.yaml"
    params:
        url=lambda wildcards: clade_url_by_lineage_and_segment.get(wildcards.lineage, {}).get(wildcards.segment),
        offset=lambda wildcards: config.get("reference_offsets", {}).get(wildcards.lineage, {}).get(wildcards.segment, 0),
    shell:
        """
        curl "{params.url}" \
            | perl -F'\\t' -ne '$F[2]+={params.offset} if $F[1] =~ "nuc"; print join "\\t", @F' > {output.clades}
        """

rule download_and_offset_subclades:
    output:
        subclades="config/{lineage}/{segment}/subclades.tsv",
    conda: "../../workflow/envs/nextstrain.yaml"
    params:
        url=lambda wildcards: subclade_url_by_lineage_and_segment.get(wildcards.lineage, {}).get(wildcards.segment),
        offset=lambda wildcards: config.get("reference_offsets", {}).get(wildcards.lineage, {}).get(wildcards.segment, 0),
    shell:
        """
        curl "{params.url}" \
            | perl -F'\\t' -ne '$F[2]+={params.offset} if $F[1] =~ "nuc"; print join "\\t", @F' > {output.subclades}
        """
```
